version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <Your-ECR-Repository-URI>

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t <Your-ECR-Repository-URI>:latest .
      - docker tag <Your-ECR-Repository-URI>:latest <Your-ECR-Repository-URI>:build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to ECR...
      - docker push <Your-ECR-Repository-URI>:latest
      - docker push <Your-ECR-Repository-URI>:build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

artifacts:
  files: 
    - imagedefinitions.json
